items:
    - idxid: "002"
      idxname: speeding
      indexingkey: speeding
      keycol: IndexableData
      filepath: /home/blockchain/fedblock/etri-index/idxmngr-go/data/kaia/speeding.bf
      network: kaia
      blocknum: 200099166
      fromblock: 199980507
      keysize: 128
      address: localhost:50052
      callcnt: 0
      keycnt: 0
      indexdatacnt: 0
    - idxid: "003"
      idxname: purpose
      indexingkey: purpose
      keycol: IndexableData
      filepath: /home/blockchain/fedblock/etri-index/idxmngr-go/data/kaia/purpose.bf
      network: kaia
      blocknum: 202932232
      fromblock: 200585534
      keysize: 64
      address: localhost:50052
      callcnt: 0
      keycnt: 0
      indexdatacnt: 0
    - idxid: "004"
      idxname: emissionItem
      indexingkey: purpose
      keycol: IndexableData
      filepath: /home/blockchain/fedblock/etri-index/idxmngr-go/data/kaia/emissionitem.bf
      network: kaia
      blocknum: 201295534
      fromblock: 200795534
      keysize: 64
      address: localhost:50052
      callcnt: 0
      keycnt: 0
      indexdatacnt: 0
    - idxid: "005"
      idxname: process
      indexingkey: purpose
      keycol: IndexableData
      filepath: /home/blockchain/fedblock/etri-index/idxmngr-go/data/kaia/process.bf
      network: kaia
      blocknum: 200199166
      fromblock: 200785522
      keysize: 64
      address: localhost:50052
      callcnt: 0
      keycnt: 0
      indexdatacnt: 0
    - idxid: "006"
      idxname: energySource
      indexingkey: purpose
      keycol: IndexableData
      filepath: /home/blockchain/fedblock/etri-index/idxmngr-go/data/kaia/energysource.bf
      network: kaia
      blocknum: 200199166
      fromblock: 199980507
      keysize: 64
      address: localhost:50052
      callcnt: 0
      keycnt: 0
      indexdatacnt: 0
    - idxid: "008"
      idxname: facility
      indexingkey: purpose
      keycol: IndexableData
      filepath: /home/blockchain/fedblock/etri-index/idxmngr-go/data/kaia/facility.bf
      network: kaia
      blocknum: 200209136
      fromblock: 200099168
      keysize: 64
      address: localhost:50052
      callcnt: 0
      keycnt: 0
      indexdatacnt: 0
    - idxid: "009"
      idxname: wasteType
      indexingkey: purpose
      keycol: IndexableData
      filepath: /home/blockchain/fedblock/etri-index/idxmngr-go/data/kaia/wastetype.bf
      network: kaia
      blocknum: 200884524
      fromblock: 200785522
      keysize: 64
      address: localhost:50052
      callcnt: 0
      keycnt: 0
      indexdatacnt: 0
    - idxid: "010"
      idxname: powerConsumption
      indexingkey: purpose
      keycol: IndexableData
      filepath: /home/blockchain/fedblock/etri-index/idxmngr-go/data/kaia/powerconsumption.bf
      network: kaia
      blocknum: 0
      fromblock: 1111111111111
      keysize: 64
      address: localhost:50052
      callcnt: 0
      keycnt: 0
      indexdatacnt: 0
