networks:
  hardhat-local:
    contract_address: '0x5FbDB2315678afecb367f032d93F642f64180aa3'
    deployed_at: '2025-10-24T01:42:37.776Z'
    network_type: hardhat-local
  monad:
    contract_address: '0x693570F190EbFaAf2E314D353849751b4f237357'
    deployed_at: '2025-10-22T01:28:58.110Z'
    network_type: monad
  kaia:
    contract_address: '0x7423fF426f31AC01dEB370C92D7aD5106e90991e'
    deployed_at: '2025-11-04T02:55:06.896Z'
    network_type: kaia
